from django.urls import path
from . import views

urlpatterns = [ path('login/', views.login, name='login'),
               path('index/', views.index, name='index'),
               path('index_vendedor/', views.index_vendedor, name='index_vendedor'), 
               path('logout/', views.logout_view, name='logout'),
               path('forgot_password/', views.forgot_password_view, name='forgot_password'),
               path('recover_password_view/', views.recover_password_view, name='recover_password_view'),
               path('recover_password/', views.recover_password, name='recover_password'),
               path('add_automovil',views.add_automovil, name='add_automovil'),
               path('edit_automovil',views.edit_automovil, name='edit_automovil'),
               path('vis_eli',views.vis_eli, name='vis_eli'),
               path('add_cliente',views.add_cliente, name='add_cliente'),
               path('edit_cliente',views.edit_cliente, name='edit_cliente'),
               path('vis_eli_cliente',views.vis_eli_cliente, name='vis_eli_cliente'),
               path('gra_repuestos',views.gra_repuestos, name='gra_repuestos'),
               path('add_vendedor',views.add_vendedor, name='add_vendedor'),
               path('edit_vendedor',views.edit_vendedor, name='edit_vendedor'),
               path('vis_eli_vendedor',views.vis_eli_vendedor, name='vis_eli_vendedor'),
               path('agregar_vehiculo',views.agregar_vehiculo, name='agregar_vehiculo'),
               path('editar_vehiculo',views.editar_vehiculo, name='editar_vehiculo'),
               path('eliminar_vehiculo',views.eliminar_vehiculo, name='eliminar_vehiculo'),
               path('agregar_vendedor',views.agregar_vendedor, name='agregar_vendedor'),
               path('editar_vendedor',views.editar_vendedor, name='editar_vendedor'),
               path('eliminar_vendedor',views.eliminar_vendedor, name='eliminar_vendedor'),
               path('agregar_cliente',views.agregar_cliente, name='agregar_cliente'),
               path('editar_cliente',views.editar_cliente, name='editar_cliente'),
               path('eliminar_cliente',views.eliminar_cliente, name='eliminar_cliente'),
               path('vis_eli_sucursal',views.vis_eli_sucursal, name='vis_eli_sucursal'),
               path('eliminar_sucursal',views.eliminar_sucursal, name='eliminar_sucursal'),
               path('edit_sucursal',views.edit_sucursal, name='edit_sucursal'),
               path('add_sucursal',views.add_sucursal, name='add_sucursal'),
               path('gra_rep_add',views.gra_rep_add, name='gra_rep_add'),
               path('vis_eli_mod_jefe',views.vis_eli_mod_jefe, name='vis_eli_mod_jefe'),
               path('clientes',views.clientes, name='clientes'),
               path('vis_mod_eli_cliente',views.vis_mod_eli_cliente, name='vis_mod_eli_cliente'),
               path('add_cotizacion',views.add_cotizacion, name='add_cotizacion'),
               path('vis_mod_eli_cotizacion',views.vis_mod_eli_cotizacion, name='vis_mod_eli_cotizacion'),
               path('add_factura',views.add_factura, name='add_factura'),
               path('vis_eli_factura',views.vis_eli_factura, name='vis_eli_factura'),
               path('add_cotizaciones',views.add_cotizaciones, name='add_cotizaciones'),
               path('vis_vehiculos',views.vis_vehiculos, name='vis_vehiculos'),
               path('jefe_taller_add',views.jefe_taller_add, name='jefe_taller_add'),
               path('cotizaciones',views.cotizaciones, name='cotizaciones'),
               path('ventas',views.ventas, name='ventas'),
               path('add_ventas',views.add_ventas, name='add_ventas'),
               
               ]