from django.urls import path,include
from . import views
from django.contrib import admin
urlpatterns = [ path('login/', views.login, name='login'),
               path('index/', views.index, name='index'),
               path('index2/', views.index2, name='index2'), 
               path('logout/', views.logout_view, name='logout'),
               path('forgot_password/', views.forgot_password_view, name='forgot_password'),
               path('recover_password_view/', views.recover_password_view, name='recover_password_view'),
               path('recover_password/', views.recover_password, name='recover_password'),
               path('add_automovil',views.add_automovil, name='add_automovil'),
               path('edit_automovil',views.edit_automovil, name='edit_automovil'),
               path('vis_eli',views.vis_eli, name='vis_eli'),
               path('add_cliente',views.add_cliente, name='add_cliente'),
               path('edit_cliente',views.edit_cliente, name='edit_cliente'),
               path('vis_eli_cliente',views.vis_eli_cliente, name='vis_eli_cliente'),
               path('add_vendedor',views.add_vendedor, name='add_vendedor'),
               path('edit_vendedor',views.edit_vendedor, name='edit_vendedor'),
               path('vis_eli_vendedor',views.vis_eli_vendedor, name='vis_eli_vendedor'),
               path('agregar_vehiculo',views.agregar_vehiculo, name='agregar_vehiculo'),
               path('editar_vehiculo',views.editar_vehiculo, name='editar_vehiculo'),
               path('eliminar_vehiculo',views.eliminar_vehiculo, name='eliminar_vehiculo'),
               path('agregar_vendedor',views.agregar_vendedor, name='agregar_vendedor'),
               path('editar_vendedor',views.editar_vendedor, name='editar_vendedor'),
               path('eliminar_vendedor',views.eliminar_vendedor, name='eliminar_vendedor'),
               path('agregar_cliente',views.agregar_cliente, name='agregar_cliente'),
               path('editar_cliente',views.editar_cliente, name='editar_cliente'),
               path('eliminar_cliente',views.eliminar_cliente, name='eliminar_cliente'),
               path('add_repuesto/', views.add_repuesto, name='add_repuesto'),
               path('agregar_repuesto/', views.agregar_repuesto, name='agregar_repuesto'),
               path('eliminar_repuesto', views.eliminar_repuesto, name='eliminar_repuesto'),
               path('vis_eli_repuesto', views.vis_eli_repuesto, name='vis_eli_repuesto'),
               path('add_sucursal/', views.add_sucursal, name='add_sucursal'),
               path('agregar_sucursal/', views.agregar_sucursal, name='agregar_sucursal'),
               path('eliminar_sucursal', views.eliminar_sucursal, name='eliminar_sucursal'),
               path('vis_eli_sucursal', views.vis_eli_sucursal, name='vis_eli_sucursal'),
               path('add_jefetaller_cliente/',views.add_cliente_jefe_taller, name='add_jefetaller_cliente'),
               path('agregar_cliente_jefe_taller/', views.agregar_jefe_taller_cliente, name='agregar_cliente_jefe_taller'),
               path('eliminar_cliente_jefe_taller/', views.eliminar_cliente_jefe_taller, name='eliminar_cliente_jefe_taller'),
               path('vis_eli_cliente_jefe_taller/', views.vis_eli_jefe_taller_cliente, name='vis_eli_cliente_jefe_taller'),
               path('consultar_repuesto_jefe_taller/', views.consultar_repuesto_jefe_taller, name='consultar_repuesto_jefe_taller'),
               path('add_ordenes_trabajo/', views.add_ordenes_trabajo, name='add_ordenes_trabajo'),
               path('agregar_ordenes_trabajo/', views.agregar_ordenes_trabajo, name='agregar_ordenes_trabajo'),
               path('eliminar_ordenes_trabajo/', views.eliminar_ordenes_trabajo, name='eliminar_ordenes_trabajo'),
               path('vis_eli_ordenes_trabajo/', views.vis_eli_ordenes_trabajo, name='vis_eli_ordenes_trabajo'),
               path('inventario_ordenes_trabajo/', views.inventario_ordenes_trabajo, name='inventario_ordenes_trabajo'),
               path('datos_grafico/', views.datos_grafico, name='datos_grafico'),
               path('gra_repuestos',views.gra_repuestos, name='gra_repuestos'),
               path('gra_rep_add/',views.gra_rep_add, name='gra_rep_add'),
               path('datos_grafico_rep/', views.datos_grafico_rep, name='datos_grafico_rep'),
               path('gra_autos/',views.gra_autos,name='gra_autos'),
               path('gra_autos_add/',views.gra_autos_add, name='gra_autos_add'),
               path('datos_grafico_autos/', views.datos_grafico_autos, name='datos_grafico_autos'),
               path('agregar_ordenes_trabajo2/', views.agregar_ordenes_trabajo2, name='agregar_ordenes_trabajo2'),
               path('generar_pdf_orden_trabajo/<str:numero_orden_trabajo>/', views.generar_pdf_orden_trabajo, name='generar_pdf_orden_trabajo'),



               
               ]
